/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Modelo.*;
import Modelo.DAORevista;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Time;
import javax.swing.JOptionPane;

/**
 *
 * @author x
 */
public class JInternalFrameRevistas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameRevistas
     */
    public JInternalFrameRevistas() {
        initComponents();
          jTextFieldNumeroRev.setEnabled(false);
    }
private void limpiarCampos(){ //Método para limpiar cajas de texto
    //Se asigna un valor vacío a todas las cajas de texto
    //Se utiliza el nombre de variable asignado
    this.jTextFieldNumeroRev.setText(""); // Set es para asignar un valor
    this.jTextFieldTituloRev.setText ("");
    this.jTextFieldAyoRev.setText ("");
    this.jTextFieldIssnRev.setText ("");
    this.jTextFieldPrecioRev.setText("");
    this.jTextFieldHoraventaRev.setText("");
}
 public void obtenerDatos(){
        List<Revista> revistas=new DAORevista().obtenerDatos();
        DefaultTableModel modelo= new DefaultTableModel();
        
        String[] columnas={"numeros","titulo","ayo",
                 "issn","precio","Horaventa"};
        
modelo.setColumnIdentifiers(columnas);
        
for(Revista revi:revistas){
    String[]renglon={Integer.toString(revi.getNumero()),
        revi.getTitulo(),
         Integer.toString(revi.getAyo()),
         revi.getIssn(),
       
       Float.toString(revi.getPrecio()),
        revi.getHoraventa().toString()};
modelo.addRow(renglon);
}
jTableRevista.setModel(modelo);
 }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumeroRev = new javax.swing.JTextField();
        jTextFieldTituloRev = new javax.swing.JTextField();
        jTextFieldIssnRev = new javax.swing.JTextField();
        jTextFieldHoraventaRev = new javax.swing.JTextField();
        jTextFieldPrecioRev = new javax.swing.JTextField();
        jTextFieldAyoRev = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonGuardarRev = new javax.swing.JButton();
        jButtonEditarRev = new javax.swing.JButton();
        jButtonActualizarRev = new javax.swing.JButton();
        jButtonBorrarRev = new javax.swing.JButton();
        jButtonBuscarRev = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRevista = new javax.swing.JTable();

        jLabel9.setText("jLabel9");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Registrar/Guardar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 6, -1, -1));
        jPanel1.add(jTextFieldNumeroRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 45, 110, -1));
        jPanel1.add(jTextFieldTituloRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 85, 110, -1));
        jPanel1.add(jTextFieldIssnRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 165, 110, -1));
        jPanel1.add(jTextFieldHoraventaRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 110, -1));
        jPanel1.add(jTextFieldPrecioRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 205, 110, -1));
        jPanel1.add(jTextFieldAyoRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 125, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 48, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Año");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Issn");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("titulo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora/Venta");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Transacciones");

        jTextFieldBuscar.setText("jTextField12");

        jButtonGuardarRev.setText("Guardar");
        jButtonGuardarRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarRevActionPerformed(evt);
            }
        });

        jButtonEditarRev.setText("Editar");
        jButtonEditarRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarRevActionPerformed(evt);
            }
        });

        jButtonActualizarRev.setText("Actualizar");
        jButtonActualizarRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarRevActionPerformed(evt);
            }
        });

        jButtonBorrarRev.setText("Borrar");
        jButtonBorrarRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarRevActionPerformed(evt);
            }
        });

        jButtonBuscarRev.setText("Buscar");
        jButtonBuscarRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarRevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBorrarRev)
                    .addComponent(jButtonGuardarRev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEditarRev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonActualizarRev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButtonBuscarRev, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarRev)
                    .addComponent(jButtonGuardarRev))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarRev)
                    .addComponent(jButtonActualizarRev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuscarRev)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTableRevista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRevista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarRevActionPerformed
        // TODO add your handling code here:
 String Titu=jTextFieldTituloRev.getText();
 int Ayo=Integer.parseInt(jTextFieldAyoRev.getText());
 String Iss=jTextFieldIssnRev.getText();
 float Preci=Float.parseFloat(jTextFieldPrecioRev.getText ());
 String Hora=jTextFieldHoraventaRev.getText();
 if(Titu.contentEquals("")||
         Ayo==0||
    Iss.contentEquals("")||
         Preci==0||
         Hora.contentEquals("")){
     JOptionPane.showConfirmDialog(rootPane,
"Todos los Campos son obligatorios");
     
    }//GEN-LAST:event_jButtonGuardarRevActionPerformed
else{
try{
 Time Hor = Time.valueOf(Hora);
Revista revi=new DAORevista().Insertar(Titu, Ayo ,Iss, Preci, Hor);
JOptionPane.showMessageDialog(rootPane, "Registro agregado");
}catch (Exception e){
     e.printStackTrace();
     JOptionPane.showMessageDialog(rootPane,"Seleccione un registro de la tabla");
}
 }
 obtenerDatos();
limpiarCampos();  
    }
    private void jButtonBorrarRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarRevActionPerformed
        // TODO add your handling code here:
        int fila=this.jTableRevista.getSelectedRow();
        if(fila==1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
        }
        else{
            int id=Integer.parseInt((String)this.jTableRevista.getValueAt(fila,0).toString());
            DAORevista dao=new DAORevista();
            dao.Eliminar(id);
            obtenerDatos();
        }
    }//GEN-LAST:event_jButtonBorrarRevActionPerformed

    private void jButtonEditarRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarRevActionPerformed
        // TODO add your handling code here:
        int fila=this.jTableRevista.getSelectedRow();
        if(fila==-1){
            JOptionPane.showConfirmDialog(rootPane, "Seleccione un registro de la tabla");
        }
        else{
            try{
                int id=Integer.parseInt((String)this.jTableRevista.getValueAt(fila,0).toString());
                String Titu=(String)this.jTableRevista.getValueAt(fila,1);
                int Ayo=Integer.parseInt((String)this.jTableRevista.getValueAt(fila,2));
                String Iss=(String)this.jTableRevista.getValueAt(fila,3);
                 float Preci=Float.parseFloat((String)this.jTableRevista.getValueAt(fila,4).toString());
                String Hora=(String)this.jTableRevista.getValueAt(fila,5);
                jTextFieldNumeroRev.setText(""+id);
                jTextFieldTituloRev.setText(Titu);
                jTextFieldAyoRev.setText(""+Ayo);
                jTextFieldIssnRev.setText(Iss);
                jTextFieldPrecioRev.setText(""+Preci);
                jTextFieldHoraventaRev.setText(Hora);
            }catch(NumberFormatException e){
                e.printStackTrace();
            
        }
         }   
    }//GEN-LAST:event_jButtonEditarRevActionPerformed

    private void jButtonBuscarRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarRevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarRevActionPerformed

    private void jButtonActualizarRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarRevActionPerformed
        // TODO add your handling code here:
         int id=Integer.parseInt(this.jTextFieldNumeroRev.getText());
         String titu=this.jTextFieldTituloRev.getText();
         int ay=Integer.parseInt(this.jTextFieldAyoRev.getText());
         String iss=this.jTextFieldIssnRev.getText();
         int pre=Integer.parseInt(this.jTextFieldPrecioRev.getText());
          Time Hora=Time.valueOf(this.jTextFieldHoraventaRev.getText()); 
          
          
          DAORevista dao=new DAORevista();
                int res=dao.Actualizar(id,titu,ay,iss,pre,Hora);
                if(res==1){
                    JOptionPane.showMessageDialog(rootPane, "¡Autor Acutalizado!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "¡Ocurrio un ERROR!");
                }
                

    }//GEN-LAST:event_jButtonActualizarRevActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarRev;
    private javax.swing.JButton jButtonBorrarRev;
    private javax.swing.JButton jButtonBuscarRev;
    private javax.swing.JButton jButtonEditarRev;
    private javax.swing.JButton jButtonGuardarRev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRevista;
    private javax.swing.JTextField jTextFieldAyoRev;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldHoraventaRev;
    private javax.swing.JTextField jTextFieldIssnRev;
    private javax.swing.JTextField jTextFieldNumeroRev;
    private javax.swing.JTextField jTextFieldPrecioRev;
    private javax.swing.JTextField jTextFieldTituloRev;
    // End of variables declaration//GEN-END:variables

    // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

