/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JInternalFrameAutores extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameAutores
     */
    public JInternalFrameAutores() {
        initComponents();
        jTextIdAutor.setEnabled(false);
    }
    public void  limpiarCampos(){
        jTextIdAutor.setText("");
        jTextNombres.setText("");
        jTextApellidos.setText("");
        jTextEmail.setText("");
        jTextCedula.setText("");
        jTextFechaNac.setText("");
}

    public void obtenerDatos(){
        List<Autor> autores=new DAOAutor().obtenerDatos();
        DefaultTableModel modelo= new DefaultTableModel();

        String[] columnas={"id_autor","nombres","apellidos",
                 "email","cedula","fechaNac"};
modelo.setColumnIdentifiers(columnas);
for(Autor au:autores){
    String[]renglon={Integer.toString(au.getId_autor()),au.getCedula(),
        au.getNombres(),au.getApellidos(),au.getEmail(),
        au.getFechaNac().toString()};
modelo.addRow(renglon);
    }
jTableAutor.setModel(modelo);
    }

    
                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextIdAutor = new javax.swing.JTextField();
        jTextNombres = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jTextCedula = new javax.swing.JTextField();
        jTextFechaNac = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBactualizar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jTextBuscar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAutor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 52, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 92, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cédula");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 132, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha Nac");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel1.add(jTextIdAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 50, 270, -1));
        jPanel1.add(jTextNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 90, 270, -1));
        jPanel1.add(jTextApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 130, 270, -1));
        jPanel1.add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 270, -1));
        jPanel1.add(jTextFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 270, -1));
        jPanel1.add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 270, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 267, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Registrar y Actualizar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 0, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 62, -1, -1));

        jBAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBAgregar.setForeground(new java.awt.Color(51, 51, 255));
        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 68, 178, 26));

        jBEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBEditar.setForeground(new java.awt.Color(51, 51, 255));
        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        jPanel3.add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 103, -1, 38));

        jBactualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBactualizar.setForeground(new java.awt.Color(51, 51, 255));
        jBactualizar.setText("Actualizar");
        jBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarActionPerformed(evt);
            }
        });
        jPanel3.add(jBactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 103, -1, 38));

        jBBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBBorrar.setForeground(new java.awt.Color(51, 51, 255));
        jBBorrar.setText("Borrar");
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(jBBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 153, 178, -1));

        jBBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBBuscar.setForeground(new java.awt.Color(51, 51, 255));
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 192, 178, -1));
        jPanel3.add(jTextBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 248, 209, 33));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Transacciones");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTableAutor);
        if (jTableAutor.getColumnModel().getColumnCount() > 0) {
            jTableAutor.getColumnModel().getColumn(1).setResizable(false);
            jTableAutor.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 33, 621, 270));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Autores Registrados");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
 String nomb=jTextNombres.getText();
String apell=jTextApellidos.getText();
String ema=jTextEmail.getText();
String ced=jTextCedula.getText();
String fecN= jTextFechaNac.getText();

if(nomb.contentEquals("")|| apell.contentEquals("")||
    ema.contentEquals("")||ced.contentEquals("")||
    fecN.contentEquals("")){
     JOptionPane.showConfirmDialog(rootPane,
"Todos los Campos son obligatorios");
}else{
try{
Date fech=Date.valueOf(fecN);
Autor au=new DAOAutor().Insertar( nomb, apell, ema,ced, fech);
JOptionPane.showMessageDialog(rootPane, "Registro agregado");
}catch (Exception e){
     e.printStackTrace();
     JOptionPane.showMessageDialog(rootPane,"Seleccione un registro de la tabla");
}
}
obtenerDatos();
limpiarCampos();
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        int fila=this.jTableAutor.getSelectedRow();
        if(fila==-1){
            JOptionPane.showConfirmDialog(rootPane, "Seleccione un registro de la taba");
        }
        else{
            try{
                int id=Integer.parseInt((String)this.jTableAutor.getValueAt(fila,0).toString());
                String nom=(String)this.jTableAutor.getValueAt(fila,1);
                String ape=(String)this.jTableAutor.getValueAt(fila,2);
                String corr=(String)this.jTableAutor.getValueAt(fila,3);
                String ced=(String)this.jTableAutor.getValueAt(fila,4);
                Date fec=Date.valueOf((String)this.jTableAutor.getValueAt(fila,5).toString());
                jTextIdAutor.setText(""+id);
                jTextNombres.setText(nom);
                jTextApellidos.setText(ape);
                jTextEmail.setText(corr);
                jTextCedula.setText(ced);
                jTextFechaNac.setText(String.valueOf(fec));
            }catch(NumberFormatException e){
                e.printStackTrace();
            }
            
        }
        


    }//GEN-LAST:event_jBEditarActionPerformed

        
    private void jBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(this.jTextIdAutor.getText());
                String nom=this.jTextNombres.getText();
                String ape=this.jTextApellidos.getText();
                String corr=this.jTextEmail.getText();
                String ced=this.jTextCedula.getText();
                Date fec=Date.valueOf(this.jTextFechaNac.getText());
                
                DAOAutor dao=new DAOAutor();
                int res=dao.Actualizar(id,nom,ape,corr,ced,fec);
                if(res==1){
                    JOptionPane.showMessageDialog(rootPane, "¡Autor Acutalizado!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "¡Ocurrio un ERROR!");
                }
   
    }//GEN-LAST:event_jBactualizarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        // TODO add your handling code here:
        int fila=this.jTableAutor.getSelectedRow();
        if(fila==1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
        }
        else{
            int id=Integer.parseInt((String)this.jTableAutor.getValueAt(fila,0).toString());
            DAOAutor dao=new DAOAutor();
            dao.Eliminar(id);
            obtenerDatos();
        }
    }//GEN-LAST:event_jBBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBactualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAutor;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFechaNac;
    private javax.swing.JTextField jTextIdAutor;
    private javax.swing.JTextField jTextNombres;
    // End of variables declaration//GEN-END:variables

}
